### ISSUE TITLE
Conditional set positioning?

### ISSUE THREAD

**Issue by jwcooper** [brendon/positioning#1]
First, thanks for the library, looks pretty interesting compared to acts_as_list (how I found it).

Is it possible to create a position that is only set if a condition is true?

Something like the following:

`positioned on: :category, column: :category_position, if: :enabled?`

This would be used in the situation where you only want a position on certain records.

If I use something like:

`positioned on: [:category, :enabled]`

That does work well, but it also creates positions for categories that are not enabled.

**Comment by jwcooper** [comment]
Hey thanks for the detailed response. 

Yea, this all makes sense. It's easy enough to just ignore those records that don't pertain to the scope of the positioning column. I tested things further and this should work well for my requirements. The tiny extra db overhead is certainly fine in this situation.

**Comment by brendon** [comment]
Thanks @jwcooper, that's great to hear. Please keep me updated on your experiences with the gem. In particular I'm keen to know if you have any issues with the Advisory Lock technique used to keep list actions sequential.

**Comment by HDias** [comment]
@jwcooper What solution solved your problem?

**Comment by jwcooper** [comment]
> @jwcooper What solution solved your problem?

I basically used my second example from my initial question. No conditional, and querying for the records I actually need. They'll still be properly ordered.
