### ISSUE TITLE
Positioned on an optional association

### ISSUE THREAD

**Issue by creativetags** [brendon/positioning#11]
I'm hitting an issue where I have a Client model: 

```
class Client < ApplicationRecord
  belongs_to :delivery, optional: true
  positioned on: :delivery, column: :delivery_position
```

Everything is fine when there is an associated delivery but they don't always have a delivery and then when I call client.update(other: 'example') I get An ArgumentError occurred in... min argument must be less than or equal to max argument

If I remove positioned on: :delivery, column: :delivery_position the error does not occur. Frustratingly, the issue only occurs in production for me. In development I run Puma and MariaDB 11.3.2 and in production Passenger MariaDB 10.11.6 - could it be related to different mariaDB versions? Apologies in advance, this is a horrible bug report.

**Comment by brendon** [comment]
That is pretty strange. I've tried to reproduce it here:

```

class TestOptionalScopePositioning < Minitest::Test
  include Minitest::Hooks

  def around
    ActiveRecord::Base.transaction do
      super
      raise ActiveRecord::Rollback
    end
  end

  def setup
    @list = List.create name: "First List"
    @first_tag = Tag.create name: "First Tag"
    @second_tag = Tag.create name: "Second Tag"
    @third_tag = Tag.create name: "Third Tag"
    @fourth_tag = @list.tags.create name: "Fourth Tag"
    @fifth_tag = @list.tags.create name: "Fifth Tag"
    @sixth_tag = @list.tags.create name: "Sixth Tag"

    @models = [
      @list, @first_tag, @second_tag,
      @third_tag, @fourth_tag, @fifth_tag, @sixth_tag
    ]

    reload_models
  end

  def reload_models
    @models.map(&:reload)
  end

  def test_that_create_works_without_scope
    assert_equal [1, 2, 3], [@first_tag, @second_tag, @third_tag].map(&:position)
    assert_equal [1, 2, 3], [@fourth_tag, @fifth_tag, @sixth_tag].map(&:position)

    assert_nil @first_tag.list
    assert_nil @second_tag.list
    assert_nil @third_tag.list
  end

  def test_that_updates_works_without_scope
    @first_tag.update name: "New Tag"

    reload_models
    assert_equal 1, @first_tag.position
    assert_nil @first_tag.list
  end

  def test_that_shuffling_works_without_scope
    @first_tag.update position: {after: @second_tag}

    reload_models
    assert_equal [1, 2, 3], [@second_tag, @first_tag, @third_tag].map(&:position)
    assert_nil @first_tag.list
  end

  def test_that_shuffling_works_from_no_scope_to_scope
    @first_tag.update list: @list

    reload_models
    assert_equal [1, 2], [@second_tag, @third_tag].map(&:position)
    assert_equal [1, 2, 3, 4], [@fourth_tag, @fifth_tag, @sixth_tag, @first_tag].map(&:position)
    assert_equal @list, @first_tag.list
  end

  def test_that_shuffling_works_from_scope_to_no_scope
    @fourth_tag.update list: nil

    reload_models
    assert_equal [1, 2, 3, 4], [@first_tag, @second_tag, @third_tag, @fourth_tag].map(&:position)
    assert_equal [1, 2], [@fifth_tag, @sixth_tag].map(&:position)
    assert_nil @fourth_tag.list
  end
end
```

The tests all pass against mysql and postgresql. I don't think it'd be a database error as that sounds like a ruby error. Perhaps paste the whole stack trace and the error and we can go from there.

**Comment by brendon** [comment]
Did you make any progress?

**Comment by creativetags** [comment]
Will take a look at this tomorrow, thanks

**Comment by creativetags** [comment]
I'm still seeing this issue after upgrading the production server to mariadb 11.3.2 unfortunately. I managed to get a little more detail on the error:
min argument must be less than or equal to max argument (ArgumentError)

        self.position = position_before_type_cast.clamp(1..last_position)
                                                        ^^^^^^^^^^^^^^^^

**Comment by brendon** [comment]
Interesting, so somehow `last_position` is less that `1`. This would only be the case inside a list shuffle but these are supposed to be protected by an advisory lock. Do you have just a single database server  for all your rails application instances or are you running some kind of distributed setup? Advisory locks only work at the database server level and rely on all instances of the app using that one server.

```
def last_position
  (positioning_scope.maximum(@column) || 0) + (in_positioning_scope? ? 0 : 1)
end
```

Next time it raises, see if you can get me a full stack trace :)

**Comment by creativetags** [comment]
It's just one database on one server.

Finally figured out how to get the trace:

positioning (0.2.2) lib/positioning/mechanisms.rb:123:in `clamp'                                                                                                                                               positioning (0.2.2) lib/positioning/mechanisms.rb:123:in `solidify_position'                                                                                                                                   positioning (0.2.2) lib/positioning/mechanisms.rb:25:in `update_position'                                                                                                                                      positioning (0.2.2) lib/positioning.rb:53:in `block in positioned'

**Comment by brendon** [comment]
Thanks for that. Does the trace go any further back to your code initiating the save? It'd be good to trace back to there and also for you to post that code here. Ideally if you have logging of the request in your production.log that shows the parameters you're attempting to save that would also help. :)

**Comment by creativetags** [comment]
Ok, I've added more details from the log to my last comment. I'm updating a parameter that has nothing to do with positioning but calling update on Client triggers positioning callbacks.

**Comment by brendon** [comment]
Thanks for that. Are you able to go into the production console or look at the database and list out all the records in that scope along with their position? I'm wondering if perhaps there's an item in there with a negative position. This could have been from before you started using this gem, or something may have gone wrong and an item has become stuck with a negative position due to a crash etc... I guess it's also possible for there to be an item with a NULL position if you haven't added the appropriate database constraints? Will be interesting to see.

**Comment by creativetags** [comment]
No negative values for the position column. I've constrained it so it can't be null:
t.integer "delivery_position", default: 1, null: false
my association id:
t.integer "delivery_id", unsigned: true

for the records throwing the error the delivery_id column is null which is correct, there hasn't been a delivery assigned yet.

**Comment by brendon** [comment]
Just a hunch but I think it’s the default value you’ve set at the database level. Try removing that and see if things improve. To be honest I’ve never done any testing with a default value in play. This used to cause problems with ranked-model.

**Comment by creativetags** [comment]
It seems the problem was related to importing new records in a way that didn't trigger callbacks. I've changed my code so they do now trigger the create callback but is there a way to fix existing records? I've tried:

`client.run_callbacks(:update)
`
but it gives the same error as before

**Comment by brendon** [comment]
I think for existing records you'll just have to execute some manual SQL with `update_all`. So just load each record and assign it an ever increasing integer value for position.

**Comment by creativetags** [comment]
Brilliant! So I was able to resolve the issue with this (for MySQL)
```
SET @start_value = 1;
UPDATE clients
SET delivery_position = (@start_value := @start_value + 1)
WHERE delivery_id IS NULL;
```

**Comment by brendon** [comment]
So good! :D Glad it wasn't to do with the gem itself (apart from perhaps it needing to be more robust). There is an open issue around how to seed existing lists. The process gets more complicated when there are scope values to deal with.
