### ISSUE TITLE
Version 0.2.2 breaks destroying parent when child association has a class_name set

### ISSUE THREAD

**Issue by jwcooper** [brendon/positioning#19]
I have a `project` with `segments` and `tasks` that all belong to a `tasks` table with positioning.

The `segments` have a `class_name: "Task"`.

When I destroy the project in 0.2.2 I get the following error as it doesn't detect that the deletion was from the `dependent: :destroy`.

```
NoMethodError: undefined method `+' for nil (NoMethodError)

        contract(positioning_scope, (position_was + 1)..)
```

I believe the issue is on this line:
https://github.com/brendon/positioning/blob/main/lib/positioning/mechanisms.rb#L185

```
      @positioned.destroyed_by_association && positioning_columns.any? do |scope_component|
        @positioned.destroyed_by_association.foreign_key == scope_component
      end
```

I don't think the foreign_key is going to match the scope_component in this case, so it falls back to the:

```
contract(positioning_scope, (position_was + 1)..)
```

section of the code.

If I lock to 0.2.1, destroying the `project` works just fine, but 0.2.2 breaks the destroy.

My `project` model defines the children as such:

```
  has_many :segments, -> { where(segment: true).order(segment_position: :asc) }, dependent: :destroy, class_name: "Task"
  has_many :tasks, -> { where(segment: false).order(position: :asc) }, dependent: :destroy
```

**Comment by brendon** [comment]
Hi @jwcooper, that's an interesting one! This would have been the commit that changed things:

https://github.com/brendon/positioning/commit/e4987022fe8aa0f01cdb624028649912f71c9f57

We started processing the delete before it happens instead of afterward just in case multiple records are being deleted at the same time. In your case I think we just need to improve the association delete detection logic. I'll see what I can dig up :)

**Comment by brendon** [comment]
I've had a further look at this and this is how we define the scope component when it's a `belongs_to` relation:

```
positioning_columns[column] = Array.wrap(on).map do |scope_component|
  scope_component = scope_component.to_s
  reflection = reflections[scope_component]

  (reflection && reflection.belongs_to?) ? reflection.foreign_key : scope_component
end
```

So we are trying to grab the `foreign_key` from the relation.

Are you able to do some debugging around the `destroyed_by_association` checks to see what is being compared?

**Comment by brendon** [comment]
Also paste in your actual model config so that I can check that.

**Comment by brendon** [comment]
Sorry, GitHub doesn't notify me when you edit your original messages so I missed the updated. Perhaps just add new ones down here?

Can you take a look at an instance of the Segment model: `reflection = segment.reflections['project']`

Is `reflection.belongs_to?` `true`? and if so, what does `reflection.foreign_key` return? Hopefully it should be `project_id`.

Actually, I think I've figured it out. You have `dependent: :destroy` on both relations but potentially aren't differentiating the scopes enough for `positioning` not to interfere with the two lists.

On your `Task` model try adding `:segment` to the positioning scope for both declarations.

**Comment by brendon** [comment]
This also looks suspiciously like something that Single Table Inheritance would solve nicely. Let Rails do the heavy lifting and have a `type` column instead of a type implemented as a boolean. Positioning is tested with STI and works well.

I'm also suspecting your `Segment` model somehow has a relation to the `Task` model which could be interfering also?

**Comment by jwcooper** [comment]
Yes, the segment model is essentially a task. A segment can have multiple tasks. In a way, it's a bit of a mess, but it works because there is a very minor difference between the two models. And now that you've mentioned it, STI would be perfect here. I'll likely refactor to do just that as soon as I can.

Screenshot of the requested output:
![image](https://github.com/user-attachments/assets/872db84b-6d77-4c1a-a5e7-5bbff8814123)

I'll give your initial suggestion a shot (adding :segment) and see if that resolves the issue, if not, will likely just explore STI.

Really appreciate the feedback on this, thank you.

**Comment by brendon** [comment]
No worries @jwcooper, always happy to help :)

To me it looks like the same thing is being destroyed twice. In the second case it'll already have a nil position perhaps?

STI definitely seems to be the least troublesome solution. If you figure anything else out let me know.

Keep the issue open until you find a way forward :D

**Comment by brendon** [comment]
How'd you get on with the scoping / STI implementation @jwcooper? :)

**Comment by jwcooper** [comment]
I've got it all worked out. End game will be migrating to STI, but I adjusted the scope and fixed one of the records trying to get destroyed twice.

Thanks again for your help!

**Comment by brendon** [comment]
Great to hear it! :D
