### ISSUE TITLE
Improve the `positioned` method by using `class_name` if provided

### ISSUE THREAD

**Issue by Mth0158** [brendon/positioning#26]
Hi,

I have been using the gem for some days and I. encountered an issue. I have the following models:

```ruby
class Camp::Lecture < ApplicationRecord
  # Configurations =============================================================
  positioned on: :group

  # Associations ===============================================================
  belongs_to :group,
             inverse_of: :lectures,
             class_name: "Camp::Lecture::Group",
             foreign_key: :camp_lecture_group_id,
             optional: true
end
```

```ruby
class Camp::Lecture::Group < ApplicationRecord
  # Configurations =============================================================

  positioned

  # Associations ===============================================================

  has_many :lectures,
           inverse_of: :group,
           class_name: "Camp::Lecture"
end
```

However, running `Camp::Lecture.heal_position_column!` fails saying:
```bash
xxx(dev)> Camp::Lecture.heal_position_column!
   (0.2ms)  SELECT pg_advisory_lock(2943946040138225658)xxx/app/models/camp/lecture.rb:9)
  Camp::Lecture Load (3.5ms)  SELECT DISTINCT group FROM "camp_lectures"
/xxx/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0/gems/irb-1.14.0/lib/irb.rb:1285:in `full_message': PG::SyntaxError: ERROR:  syntax error at or near "group" (ActiveRecord::StatementInvalid)
LINE 1: SELECT DISTINCT group FROM "camp_lectures"
```
I made it work by changing:
```ruby
positioned on: :group
```

by
```ruby
positioned on: :camp_lecture_group_id
```

It could be nice, if possible, that when using an association, it looks for the table declared by the `class_name` option if provided in the `belongs_to` method.
This would make the code more explicit and maintainable.

What do you think? (I might also be using the gem wrong)

**Comment by brendon** [comment]
Hi @Mth0158, it should be looking at the relation and grabbing the foreign key:

https://github.com/brendon/positioning/blob/d854918c1ee769a0e74fe8d06d38b2d7d2075238/lib/positioning.rb#L32-L37

I think you just have to declare your `belongs_to` before you call `positioned` (code order) as these are called when Rails boots and are executed in the order you have them in the code. Hope that makes sense :D
