### ISSUE TITLE
Healer causes DB error when model has a default_scope

### ISSUE THREAD

**Issue by dallas** [brendon/positioning#31]
If a model uses both positioning and a `default_scope`, the `heal_{name}_column!` helper will most likely not work correctly. If the `default_scope` tries to operate on any columns not in the healer’s `select`, it will cause the DB to have an error.

For example (taken from #27):

> When using an ordering default scope in the model, the query generated by the healer with `model.select(*positioning_columns).distinct` is invalid:
>
> ```
> ERROR:  for SELECT DISTINCT, ORDER BY expressions must appear in select list (PG::InvalidColumnReference)
> ```
>
> With a `default_scope` that orders the records, Rails automatically adds the default scope to all queries, including the `SELECT > DISTINCT` above. This breaks the healer, because it does not add the default ordering scope to the `select` list. Unscoping the query before selecting removes the default query and makes the healer work. This should not impact other functionality, since any ordering required when healing must be passed explicitely [sic] anyway.

**Comment by brendon** [comment]
@LukasSkywalker has disappeared on me. I'll just close that PR and apply my own fix :)

**Comment by brendon** [comment]
Released as 0.4.5.

**Comment by dallas** [comment]
Awesome! Thank you for the super quick response! 🙌  🙇

**Comment by brendon** [comment]
No worries at all :D I'd been meaning to sort this one out :)

**Comment by moQuez** [comment]
so nice this got sorted out, I was about to post something but now I just needed to update :)

Thanks for this gem @brendon 🥇

**Comment by brendon** [comment]
> so nice this got sorted out, I was about to post something but now I just needed to update :)
> 
> Thanks for this gem @brendon 🥇

You're most welcome @moQuez :D
