### ISSUE TITLE
Set updated_at on affected items

### ISSUE THREAD

**Issue by pettersj** [brendon/positioning#32]
When an items position is updated, some other items in that lists position is also updated. However, their "updated_at" column is not affected, which is bad for caching. Would it be possible to add as an option to set the "updated_at" timestamp when affected items position is updated?

(PS: I found this project on acts_as_list, and this seems to be working great!)

**Comment by brendon** [comment]
Hi @pettersj, that's an interesting point. Right now we're using `update_all` in order not to mess with anything else on the row. In terms of caching however, wouldn't it be better to have a `belongs_to :parent_relation, touch: true` and then hang your cache off of the parent relation's `updated_at`? That way when you reorder the record it'll fire off the touch to the parent to signal that things have changed at the list level. The item that is the focus the reorder definitely will update it's `updated_at` also.

Let me know what you're think.

Thanks for the great feedback too! This has been something I've wanted to do for a long time so it's great to see people using it and enjoying it :)

**Comment by brendon** [comment]
Did that help at all? :)

**Comment by brendon** [comment]
Just checking if I should close this now @pettersj

**Comment by brendon** [comment]
Closing due to no reply.
