### ISSUE TITLE
Add support for removing the position?

### ISSUE THREAD

**Issue by MiltonRen** [brendon/positioning#8]
Not sure if this makes sense in this gem with acts_as_list I can remove an item from the list, which I would love to have here : )

**Comment by brendon** [comment]
Hi @MiltonRen :) In `positioning` everything is in a list, so if you want to have a 'not in the list' kind of setup you'd need to add a boolean column to the table called something like `in_list` and then use that in your scope:

`positioned on: [:category, :in_list]`

To remove the item, you'd just `item.update in_list: false`.

Of course replace variable and scope names as you wish.
